services:
  - type: web
    name: gold-pulse
    env: node
    plan: free
    buildCommand: |
      npm install -g @nestjs/cli && \
      npm install && \
      nest build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - package.json
        - src/**
        - tsconfig.json
        - nest-cli.json
        - webpack.config.js