services:
  - type: web
    name: gold-pulse
    env: node
    nodeVersion: 20.x
    buildCommand: |
      echo "Starting build..." && \
      npm ci && \
      npm run build && \
      echo "Build complete!"
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - src/**
        - tsconfig.json
        - nest-cli.json
    disk:
      name: gold-pulse-cache
      mountPath: /opt/render/project/src
      sizeGB: 1 