services:
  - type: web
    name: gold-pulse
    env: node
    nodeVersion: 20.x
    buildCommand: |
      npm cache clean --force
      rm -rf node_modules package-lock.json
      npm install --legacy-peer-deps --force --no-package-lock --no-audit --no-fund
      npm install -g @nestjs/cli
      npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /
    installCommand: npm install --legacy-peer-deps --force --no-package-lock --no-audit --no-fund 