services:
  - type: web
    name: gold-pulse
    env: node
    plan: free
    nodeVersion: 20.11.1
    buildCommand: |
      echo "Starting build process..." && \
      echo "Current Node version:" && node -v && \
      echo "Current NPM version:" && npm -v && \
      echo "Cleaning npm cache and node_modules..." && \
      rm -rf node_modules && \
      rm -rf .npm && \
      npm cache clean --force && \
      echo "Installing dependencies..." && \
      npm install --legacy-peer-deps --verbose && \
      echo "Installing dev dependencies..." && \
      npm install --legacy-peer-deps --save-dev --verbose && \
      echo "Installing type definitions..." && \
      npm install --save-dev @types/node@20.10.4 @types/jest@29.5.11 --verbose && \
      echo "Verifying TypeScript installation..." && \
      npx tsc --version && \
      echo "Listing node_modules/@types..." && \
      ls -la node_modules/@types && \
      echo "Building application..." && \
      NODE_OPTIONS="--max-old-space-size=2048" npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NODE_DEBUG
        value: "*"
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - package.json
        - src/**
        - tsconfig.json
        - nest-cli.json
        - webpack.config.js