services:
  - type: web
    name: gold-pulse
    env: node
    nodeVersion: 20.x
    buildCommand: npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /
    installCommand: npm ci --only=production --legacy-peer-deps
    autoDeploy: true
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - src/**
        - tsconfig.json
        - nest-cli.json
        - webpack.config.js
    disk:
      name: gold-pulse-cache
      mountPath: /opt/render/project/src
      sizeGB: 1 