services:
  - type: web
    name: gold-pulse
    env: node
    nodeVersion: 20.x
    buildCommand: |
      echo "Starting build..." && \
      rm -rf node_modules package-lock.json && \
      npm install && \
      npm run build && \
      echo "Build complete!"
    startCommand: node dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true
    buildFilter:
      paths:
        - package.json
        - src/**
    disk:
      name: gold-pulse-cache
      mountPath: /opt/render/project/src
      sizeGB: 1 